# Generated by Django 5.2.6 on 2025-09-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.URLField(blank=True)),
                ('tipo', models.CharField(max_length=50)),
                ('episodios', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('nota', models.FloatField(blank=True, null=True)),
                ('generos', models.ManyToManyField(related_name='animes', to='animes.genero')),
            ],
        ),
    ]
