# Generated by Django 5.2.6 on 2025-09-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='episodios',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='nota',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='status',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='tipo',
        ),
        migrations.AddField(
            model_name='anime',
            name='data_lancamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='sinopse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
