# Generated by Django 5.2.6 on 2025-09-13 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0002_remove_anime_descricao_remove_anime_episodios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='data_lancamento',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='anime',
            name='sinopse',
            field=models.TextField(blank=True),
        ),
    ]
